<?php defined('SYSPATH') OR die('No direct access allowed.');
class Bars_Controller  extends drinkrecept_Core {
	public function index()
	{   
        xml::toXML(array("template" => 'bars'), $this->xml_root);
        $sql = "select name, bid from bars where public = 1 order by name asc";
        $bars = $this->db->query($sql)->as_array(true);
        $barArr = array();
        foreach($bars as $bar){
            $barArr[count($barArr)."bar"] = array("@bid" => $bar['bid'], 'name' => $bar['name']);
        }

        xml::toXML(array('bars' => $barArr), $this->xml_root);
    }
    public function save($bid = NULL){
        xml::toXML(array("template" => 'savebar'), $this->xml_root);
        $bar = new bar();
        $db = Database::instance();
        if($bid != NULL){
            $sql = "select name from bars where bid = ".$bid;
            $names = $db->query($sql)->as_array(TRUE);
            if($count($names)){
                xml::toXML(array('barname' => $names[0]['name']), $this->xml_root);
            } else {
                xml::toXML(array('barname' => ''), $this->xml_root);
            }
        }
    }
	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo __('This text is generated by __call. If you expected the index page, you need to use: :uri:',
				array(':uri:' => Router::$current_uri));
	}
} // End Welcome Controller
