<?php defined('SYSPATH') OR die('No direct access allowed.');
class controller_Category  extends controller_drinkrecept {
	public function index()
	{
        $sql = 'select cid, name from categories order by name asc';
        $r = $this->db->query($sql)->as_array(true);
        $cats = array();
        foreach($r as $row){
            $cats[count($cats).'category'] = array('@href' => '/category/'.$row['cid'], 'name' => $row['name']);
        }
        xml::toXML(array("template" => 'list'), $this->xml_root);
        xml::toXML(array('list' => listgen::genList($cats)), $this->xml_root);
	}
    public function spirit($cid){
        xml::toXML(array("template" => 'category'), $this->xml_root);
        $sql = 'select * from categories where cid = '.$cid;
        list($cat) = $this->db->query($sql)->as_array(true);
        xml::toXML(array('category' => $cat), $this->xml_root);
    }


	public function __call($method, $arguments)
	{
        if(is_numeric($method)){
            $this->spirit($method);
        } else {
            // Disable auto-rendering
            $this->auto_render = FALSE;

            // By defining a __call method, all pages routed to this controller
            // that result in 404 errors will be handled by this method, instead of
            // being displayed as "Page Not Found" errors.
            echo __('This text is generated by __call. If you expected the index page, you need to use: :uri:',
                    array(':uri:' => Router::$current_uri));
        }
	}
} // End Welcome Controller
