<?php defined('SYSPATH') OR die('No direct access allowed.');
class controller_Drinklist extends controller_drinkrecept {
    public function action_index()
	{
        xml::toXML(array("template" => 'list'), $this->xml_root);
        $sql = "select did, name from drink order by name asc";
        //$drinks = $this->db->query($sql)->as_array(true);
        $drinks = DB::select_array(array('did', 'name'))->from('drink')->order_by('name', 'asc')->execute()->as_array();
        foreach($drinks as &$d){
            $d = array('@href' => '/drinks/'.$d['did'], 'name' => $d['name']);
        }

        $drinks = array("list" => Model::factory('listgen')->genList($drinks));
        xml::toXML($drinks, $this->xml_root);
	}

	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo __('This text is generated by __call. If you expected the index page, you need to use: :uri:',
				array(':uri:' => Router::$current_uri));
	}

} // End Welcome Controller
