<?php defined('SYSPATH') OR die('No direct access allowed.');
class controller_mydrinks  extends controller_drinkrecept {
	public function action_index()
	{
        xml::toXML(array("template" => 'mydrinks'), $this->xml_root);
        $myDrinks = array();
        foreach(Model::factory('bar')->getDrinks() as $did => $name){
            $myDrinks[count($myDrinks)."drink"] = array('did' => $did, 'name' => $name);
        }
        xml::toXML(array('mydrinks' => $myDrinks), $this->xml_root);

        // Write to screen
	}


	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo __('This text is generated by __call. If you expected the index page, you need to use: :uri:',
				array(':uri:' => Router::$current_uri));
	}

} // End Welcome Controller
