<?php defined('SYSPATH') OR die('No direct access allowed.');
class Welcome_Controller  extends drinkrecept_Core {
	public function index()
	{
        xml::toXML(array("template" => 'drink'), $this->xml_root);
        xml::toXML($information, $this->xml_root);
        
	}
	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo __('This text is generated by __call. If you expected the index page, you need to use: :uri:',
				array(':uri:' => Router::$current_uri));
	}

} // End Welcome Controller
