<?php defined('SYSPATH') OR die('No direct access allowed.');
class Controller_welcome extends controller_drinkrecept {
	public function action_index()
	{
        xml::toXML(array("template" => 'drink'), $this->xml_root);
        $rand = DB::select_array(array('did','name'))->from('drink')->order_by(DB::expr('RAND()'))->limit(1)->execute()->as_array();
        $rand = $rand[0]['did'];

        $information = DB::select_array(array('did', 'name', 'instructions', 'image'))->from('drink')->where('did', '=', $rand)->execute()->as_array();;
        $information = $information[0];
        $contents = DB::select_array(array('ingredients.iid', 'contents.amount', 'ingredients.name'))
            ->from('ingredients')
            ->join('contents')
            ->on('ingredients.iid', '=', 'contents.iid')
            ->where('contents.did', '=', $rand)
            ->order_by('contents.amount', 'desc')
            ->execute()
            ->as_array();
        $cont = array();
        foreach($contents as $c){
            $cont[count($cont)."ing"] = $c;
        }
        unset($c, $contents);

        $this->current_drink = $rand;

        $information = array("information" => array_merge($information, array("content" => $cont)));
//        var_dump($this->xml_root->);
        xml::toXML($information, $this->xml_root);


	}


	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo __('This text is generated by __call. If you expected the index page, you need to use: :uri:',
				array(':uri:' => Router::$current_uri));
	}

} // End Welcome Controller
